services:
 nifi_docker:
  build: ./image
  restart: always
  networks:
    vpcbr:
      ipv4_address: 172.29.0.2
  container_name: nifi_docker
  ports:
   - 8443:8443
  environment:
   - NIFI_WEB_HTTPS_PORT=8443
   - NIFI_WEB_PROXY_HOST=172.27.186.71:8443,nifi.waski.xyz:443
   - SINGLE_USER_CREDENTIALS_USERNAME=TuguRe
   - SINGLE_USER_CREDENTIALS_PASSWORD=TuguR3jkt2023
  volumes:
   #- /nifi/archive:/opt/nifi/nifi-current/conf/archive
   - /nifi/conf:/opt/nifi/nifi-current/conf
   #- /nifi/bootstrap.conf:/opt/nifi/nifi-current/conf/bootstrap.conf
   #- /nifi/login-identity-providers.xml:/opt/nifi/nifi-current/./conf/login-identity-providers.xml
   - /etc/hosts:/etc/hosts
   - /nifi:/nifi
   - /nifi/content_repository:/opt/nifi/nifi-current/content_repository
   - /nifi/database_repository:/opt/nifi/nifi-current/database_repository
   - /nifi/flowfile_repository:/opt/nifi/nifi-current/flowfile_repository
   #- /nifi/state:/opt/nifi/nifi-current/state
   #- /nifi/logs:/opt/nifi/nifi-current/logs

networks:
  vpcbr:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.29.0.0/24
